# Generated by Django 5.2.9 on 2025-12-25 05:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obligations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Marked Overdue'), ('UPDATED', 'Updated')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='obligations.obligation')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed action, null for system', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['obligation', 'created_at'], name='audit_event_obligat_ff9166_idx'), models.Index(fields=['user', 'created_at'], name='audit_event_user_id_8aca5d_idx')],
            },
        ),
    ]
