# Generated by Django 5.2.9 on 2025-12-25 05:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('due_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('owed_by', models.ForeignKey(help_text='Person who owes the obligation', on_delete=django.db.models.deletion.CASCADE, related_name='obligations_as_ower', to=settings.AUTH_USER_MODEL)),
                ('owed_to', models.ForeignKey(help_text='Person to whom the obligation is owed', on_delete=django.db.models.deletion.CASCADE, related_name='obligations_as_requester', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'obligations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owed_by', 'status', 'due_at'], name='obligations_owed_by_cc641b_idx'), models.Index(fields=['owed_to', 'status', 'due_at'], name='obligations_owed_to_fc453e_idx'), models.Index(fields=['status', 'due_at'], name='obligations_status_f69a97_idx')],
            },
        ),
    ]
