# Generated by Django 5.2.9 on 2025-12-25 05:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obligations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NEW_OBLIGATION', 'New Obligation Created'), ('COMPLETED', 'Obligation Completed'), ('OVERDUE', 'Obligation Overdue'), ('ESCALATION', 'Escalation'), ('REMINDER', 'Reminder')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('obligation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='obligations.obligation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at', 'created_at'], name='notificatio_user_id_4fb54c_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_7336fd_idx')],
            },
        ),
    ]
